# Conexión a PostgreSQL (Puerto por defecto 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/agrimensura
spring.datasource.username=postgres
spring.datasource.password=Juan1998
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto y comportamiento mágico (Crea las tablas automáticamente)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Para ver las consultas SQL en la consola del IDE
spring.jpa.show-sql=true