# Conexión a PostgreSQL (usa variables de entorno; con defaults para desarrollo local)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/agrimensura}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=Juan1998
spring.datasource.driver-class-name=org.postgresql.Driver
 
# Dialecto y comportamiento (Crea/actualiza las tablas automáticamente)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
 
# Para ver las consultas SQL en la consola del IDE
spring.jpa.show-sql=true